language: node_js
node_js: 6
git:
  depth: 5
cache:
  directories:
  - "./node_modules"
  - npm run test:integration
script:
- npm run lint
after_script:
- npm run coverage
- npm run countLOC:details

